Repository opensearch-project/alerting, pull requests merged in 2022-11, with the labels that each got.

#635 Support to specify backend roles for monitors
  .github/workflows/security-test-workflow.yml
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/SecureTransportAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt
  alerting/src/test/kotlin/org/opensearch/alerting/AccessRoles.kt
  alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureDestinationRestApiIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailAccountRestApiIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureEmailGroupsRestApiIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
Labels: documentation, backport 2.x, backport 2.4

#647 Add 2.4 release notes
  release-notes/opensearch-alerting.release-notes-2.4.0.0.md
Labels: backport 2.x, backport 2.4

#653 create findingIndex bugfix
  alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt
Labels: backport 2.x, backport 2.4

#663 create findingIndex bugfix
  alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt
Labels: backport 2.x

#675 set lastnotification time as created time for new bucket level monitor
  alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt
Labels: backport 2.x, backport 2.4
