Repository opensearch-project/alerting, pull requests merged in 2022-07, with the labels that each got.

#485 Added 2.1 release notes.
  release-notes/opensearch-alerting.release-notes-2.1.0.0.md
Labels: v2.1.0, backport 2.1, backport 2.x

#472 Add support for reproducible builds
  build.gradle
Labels: backport 2.x

#489 Staging for version increment automation
  build.gradle
Labels: backport 1.x, backport 1.3, backport 2.1, backport 2.x
