Repository opensearch-project/alerting, pull requests merged in 2022-10, with the labels that each got.

#598 add tags to trigger condition of doc-level monitor
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
Labels: backport 2.x

#601 Added groupId as org.opensearch.plugin in pluginZip publication
  alerting/build.gradle
Labels: backport 2.x, v2.4.0

#585 fix for windows ktlint issue
  .github/workflows/test-workflow.yml
  alerting/src/test/kotlin/org/opensearch/alerting/TriggerServiceTests.kt
  scripts/build.sh
Labels: backport 1.x, backport 1.3, backport 2.x, backport 2.3
