Repository opensearch-project/alerting, pull requests merged in 2022-09, with the labels that each got.

#548 Deprecate the Master nomenclature in 2.3
  alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/DestinationMigrationCoordinator.kt
Labels: backport 2.x, backport 2.3

#551 Added 2.3 release notes.
  release-notes/opensearch-alerting.release-notes-2.3.0.0.md
Labels: v2.3.0, backport 2.3

#570 Disable ktlint for alerting as it has errors on Windows
  scripts/build.sh
Labels: bug, windows, backport 2.x, backport 2.3
