Repository opensearch-project/alerting, pull requests merged in 2023-08, with the labels that each got.

#1064 fix get alerts API alertState query filter
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt
Labels: backport 2.x, backport main

#1067 Update actionGet to SuspendUntil for ClusterMetrics
  alerting/src/main/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/SupportedClusterMetricsSettingsExtensions.kt
  alerting/src/test/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatIndicesWrappersIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatShardsWrappersIT.kt
Labels: backport 2.x, backport 2.9

#1071 add alertId parameter in get chained alert API and paginate associated alerts if alertId param is mentioned
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetWorkflowAlertsAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetWorkflowAlertsAction.kt
  alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt
Labels: backport 2.x, backport 2.9

#1092 Backports #1079 (Chained Alert Behaviour Changes )
  alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/TriggerService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/script/ChainedAlertTriggerExecutionContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetWorkflowAlertsAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/CompositeWorkflowRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/WorkflowRunner.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
Labels: backport 2.x

#1094 upgrade google guava 32.0.1 to resolve CVE CVE-2023-2976
  core/build.gradle
Labels: backport 2.x

#1102 Change version to jdk 11 for maven publish
  .github/workflows/maven-publish.yml
Labels: alerting

#1079 Chained Alert Behaviour Changes
  alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/TriggerService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/script/ChainedAlertTriggerExecutionContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetWorkflowAlertsAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/CompositeWorkflowRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/WorkflowRunner.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
Labels: backport 2.x, backport 2.9
