Repository opensearch-project/alerting, pull requests merged in 2023-07, with the labels that each got.

#981 fix alert constructor with noop trigger to use execution id and workflow id
  alerting/build.gradle
  alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/main/resources/org/opensearch/alerting/alerts/alert_mapping.json
Labels: backport 2.x

#978 Fixed search monitor API to return alert counts.
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestSearchMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportSearchMonitorAction.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt
Labels: backport 2.x, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8

#968 Check if AD backend role is enabled
  alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt
  alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerServiceIT.kt
Labels: backport 2.x

#991 Fix getAlerts RBAC problem
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
Labels: backport 2.x, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9

#997 [Backport 2.x] Fix getAlerts RBAC problem (#991)
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
Labels: backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9

#964 [BucketLevelMonitor] Multi-term agg support
  alerting/src/main/kotlin/org/opensearch/alerting/TriggerService.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerServiceIT.kt
Labels: backport 2.x, backport 2.9

#976 Adds chained alerts
  alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt
  alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/QueryLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/TriggerService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/WorkflowService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/GetMonitorResponse.kt
  alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertMover.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/parsers/ChainedAlertExpressionParser.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/parsers/ChainedAlertExpressionRPNBaseParser.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/parsers/ExpressionParser.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/resolvers/ChainedAlertRPNResolver.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/resolvers/ChainedAlertTriggerExpression.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/resolvers/ChainedAlertTriggerResolver.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/tokens/CAExpressionOperator.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/tokens/CAExpressionToken.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/tokens/ChainedAlertExpressionConstant.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/tokens/ExpressionToken.kt
  alerting/src/main/kotlin/org/opensearch/alerting/model/ChainedAlertTriggerRunResult.kt
  alerting/src/main/kotlin/org/opensearch/alerting/model/WorkflowRunResult.kt
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestAcknowledgeChainedAlertsAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestExecuteWorkflowAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetWorkflowAlertsAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/script/ChainedAlertTriggerExecutionContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/service/DeleteMonitorService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportAcknowledgeChainedAlertAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteWorkflowAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteWorkflowAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetWorkflowAlertsAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/ScheduledJobUtils.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/CompositeWorkflowRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/WorkflowRunContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/WorkflowRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/WorkflowRunnerService.kt
  alerting/src/test/kotlin/org/opensearch/alerting/AlertServiceTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt
  alerting/src/test/kotlin/org/opensearch/alerting/action/GetMonitorResponseTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/chainedAlertCondition/ChainedAlertsExpressionParserTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/chainedAlertCondition/ChainedAlertsExpressionResolveTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt
  core/src/main/resources/mappings/scheduled-jobs.json
Labels: backport 2.x, backport 2.9

#1007 Backport 2.x Adds chained alerts (#976)
  alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt
  alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/QueryLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/TriggerService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/WorkflowService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/GetMonitorResponse.kt
  alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertMover.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/parsers/ChainedAlertExpressionParser.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/parsers/ChainedAlertExpressionRPNBaseParser.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/parsers/ExpressionParser.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/resolvers/ChainedAlertRPNResolver.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/resolvers/ChainedAlertTriggerExpression.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/resolvers/ChainedAlertTriggerResolver.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/tokens/CAExpressionOperator.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/tokens/CAExpressionToken.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/tokens/ChainedAlertExpressionConstant.kt
  alerting/src/main/kotlin/org/opensearch/alerting/chainedAlertCondition/tokens/ExpressionToken.kt
  alerting/src/main/kotlin/org/opensearch/alerting/model/ChainedAlertTriggerRunResult.kt
  alerting/src/main/kotlin/org/opensearch/alerting/model/WorkflowRunResult.kt
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestAcknowledgeChainedAlertsAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestExecuteWorkflowAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetWorkflowAlertsAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/script/ChainedAlertTriggerExecutionContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/service/DeleteMonitorService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportAcknowledgeChainedAlertAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteWorkflowAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteWorkflowAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetWorkflowAlertsAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/ScheduledJobUtils.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/CompositeWorkflowRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/WorkflowRunContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/WorkflowRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/WorkflowRunnerService.kt
  alerting/src/test/kotlin/org/opensearch/alerting/AlertServiceTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt
  alerting/src/test/kotlin/org/opensearch/alerting/action/GetMonitorResponseTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/chainedAlertCondition/ChainedAlertsExpressionParserTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/chainedAlertCondition/ChainedAlertsExpressionResolveTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt
  core/src/main/resources/mappings/scheduled-jobs.json
Labels: backport 2.9

#992 Implemented support for configuring a cluster metrics monitor to call cat/indices, and cat/shards.
  alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/settings/SupportedClusterMetricsSettings.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/IndexUtils.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatIndicesHelpers.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatShardsHelpers.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/SupportedClusterMetricsSettingsExtensions.kt
  alerting/src/main/resources/org/opensearch/alerting/settings/supported_json_payloads.json
  alerting/src/test/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatIndicesWrappersIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatShardsWrappersIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/SupportedClusterMetricsSettingsExtensionsTests.kt
Labels: backport 2.x, backport 2.9

#1010 Added 2.9 release notes.
  release-notes/opensearch-alerting.release-notes-2.9.0.0.md
Labels: backport 2.x, backport 2.9

#1014 Add workflowIds field in getAlerts API
  alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertMover.kt
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetAlertsAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportSearchMonitorAction.kt
  alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt
Labels: backport 2.x, backport 2.9

#1020 Fix get alerts api to also return chained alerts with default params. and skip audit state alerts
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorMetadataService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetWorkflowAlertsAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/CompositeWorkflowRunner.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
Labels: backport 2.9

#1041 fix password argument in SecureRestClientBuilder constructor for SecureWorkflowRestApiIT
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureWorkflowRestApiIT.kt
Labels: backport 2.9

#1029 Upgrade the backport workflow
  .github/workflows/backport.yml
Labels: backport 2.x
