Repository opensearch-project/alerting, pull requests merged in 2023-05, with the labels that each got.

#856 DocLevel Monitor - generate findings when 0 triggers
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerServiceIT.kt
Labels: backport 2.x, backport 2.7

#894 Fixed a bug that prevented alerts from being generated for doc level monitors that use wildcard characters in index names.
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorMetadataService.kt
  alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
Labels: backport 2.0, backport 2.1, backport 2.x, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7

#892 DocLevelMonitor Error Alert - rework
  alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt
Labels: backport 2.x, backport 2.5, backport 2.7

#905 DocLevelMonitor Error Alert revisit
  alerting/src/main/kotlin/org/opensearch/alerting/AlertService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
Labels: backport 2.x

#899 Update codeowners and maintainers
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x

#900 log error messages and clean up monitor when indexing doc level queries or metadata creation fails
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureMonitorRestApiIT.kt
Labels: backport 2.x, backport 2.7

#931 revert to deleting monitor metadata after deleting doc level queries to fix delete monitor regression.
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteMonitorAction.kt
Labels: backport 2.x, backport 2.7

#939 Added 2.8 release notes
  release-notes/opensearch-alerting.release-notes-2.8.0.0.md
Labels: backport 2.x
