Repository opensearch-project/alerting, pull requests merged in 2023-02, with the labels that each got.

#758 [BUG] ExecuteMonitor inserting metadata doc during dry run
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorMetadataService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteMonitorAction.kt
  alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt
Labels: backport 2.x, backport 2.5

#776 Adjusting max field index setting dynamically for query index
  alerting/build.gradle
  alerting/src/main/java/org/opensearch/percolator/PercolateQueryBuilderExt.java
  alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt
  core/src/main/resources/settings/doc-level-queries.json
Labels: backport 2.x, backport 2.5

#750 Fix setting default title only when no subject has been set
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/destinationmigration/NotificationApiUtils.kt
Labels: backport 2.x, backport 2.5

#804 minor fix to prevent flaky tests in downstream plugins
  core/src/main/resources/mappings/scheduled-jobs.json
Labels: backport 2.x

#805 Publish snapshots to maven via GHA
  .github/workflows/maven-publish.yml
  alerting/build.gradle
Labels: backport 2.x

#784 Multiple indices support in DocLevelMonitorInput
  alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerExecutionContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/IndexUtils.kt
  alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
Labels: backport 2.x

#809 Added 2.6 release notes.
  release-notes/opensearch-alerting.release-notes-2.6.0.0.md
Labels: backport 2.x

#812 revert enabled field in source_to_query_index_mapping
  core/src/main/resources/mappings/scheduled-jobs.json
Labels: backport 2.x, backport 2.6
