Repository opensearch-project/alerting, pull requests merged in 2023-01, with the labels that each got.

#728 Added unwrapping exceptions from core
  alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt
Labels: backport 2.x

#735 Add option to run bwc tests against bundle
  alerting/build.gradle
  alerting/src/test/resources/esnode-key.pem
  alerting/src/test/resources/esnode.pem
  alerting/src/test/resources/kirk-key.pem
  alerting/src/test/resources/kirk.pem
  alerting/src/test/resources/root-ca.pem
Labels: backport 2.5

#726 fix percolator mapping error when having field name 'type'
  alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
Labels: backport 2.x, backport 2.5

#743 Added 2.5 release notes.
  release-notes/opensearch-alerting.release-notes-2.5.0.0.md
Labels: backport 2.x, backport 2.5

#757 Dev guide update to include building/using local os-min distro
  DEVELOPER_GUIDE.md
Labels: backport 2.x

#768 fix for ERROR alert state generation in doc-level monitors
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
Labels: backport 2.x
