Repository opensearch-project/alerting, pull requests merged in 2023-11, with the labels that each got.

#1242 change Thread.sleep to waitUntil function under test files
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerServiceIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/bwc/AlertingBackwardsCompatibilityIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/util/destinationmigration/DestinationMigrationUtilServiceIT.kt
Labels: backport 2.x

#1306 Added 2.11.1 release notes.
  release-notes/opensearch-alerting.release-notes-2.11.1.0.md
Labels: backport 2.x, backport 2.11, v2.11.1

#1310 fix workflow security tests in alerting
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureWorkflowRestApiIT.kt
Labels: backport 2.x, backport 2.11

#1305 Reference get monitor and search monitor action / request / responses from common-utils
  alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/GetMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/GetMonitorRequest.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/GetMonitorResponse.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/SearchMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/SearchMonitorRequest.kt
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestSearchMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportAcknowledgeAlertAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetFindingsAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportSearchMonitorAction.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/action/GetMonitorActionTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/action/GetMonitorRequestTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/action/GetMonitorResponseTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/action/SearchMonitorActionTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/action/SearchMonitorRequestTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt
Labels: backport 2.x
