Repository opensearch-project/alerting, pull requests merged in 2023-10, with the labels that each got.

#1205 Add primary first calls for different monitor types
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt
Labels: backport 2.x

#1220 fix workflow execution for first run
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexWorkflowAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/CompositeWorkflowRunner.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt
Labels: backport 2.x

#1223 Add logging for execution and indexes of monitors and workflows
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteWorkflowAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexMonitorAction.kt
Labels: backport 2.0, backport 2.1, backport 2.x, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9, backport 2.10

#1227 fix workflow execution for first run
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportIndexWorkflowAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/CompositeWorkflowRunner.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/WorkflowRestApiIT.kt
Labels: backport 2.11

#1218 Reduce log level for informative message
  alerting/src/main/kotlin/org/opensearch/alerting/alerts/AlertIndices.kt
Labels: backport 2.x

#1250 [PR]Ensure Github workflow runs on docker image used by Production Distribution Build
  .github/workflows/bwc-test-workflow.yml
  .github/workflows/dco.yml
  .github/workflows/get-ci-image-tag.yml
  .github/workflows/multi-node-test-workflow.yml
  .github/workflows/security-test-workflow.yml
  .github/workflows/test-workflow.yml
Labels: enhancement, infrastructure, backport 2.x

#1251 Drafted 2.11 release notes.
  release-notes/opensearch-alerting.release-notes-2.11.0.0.md
Labels: backport 2.x, backport 2.11

#1264 [PR2]Ensure Github workflow runs on docker image used by Production Distribution Build
  .github/workflows/get-ci-image-tag.yml
  .github/workflows/multi-node-test-workflow.yml
  .github/workflows/security-test-workflow.yml
  .github/workflows/test-workflow.yml
Labels: enhancement, infrastructure, backport 2.x

#1245 Changed @Ignore to @AwaitsFix
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureWorkflowRestApiIT.kt
Labels: backport 2.x

#1271 [PR3]Ensure Github workflow runs on docker image used by Production Distribution Build alerting
  .github/workflows/multi-node-test-workflow.yml
  .github/workflows/test-workflow.yml
Labels: enhancement, infrastructure, backport 2.x
