Repository opensearch-project/alerting, pull requests merged in 2023-09, with the labels that each got.

#1097 optimize doc-level monitor workflow for index patterns
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/IndexUtils.kt
  alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
Labels: backport 2.x

#1115 Updates demo certs used in integ tests
  alerting/src/test/resources/sample.pem
  alerting/src/test/resources/test-kirk.jks
Labels: backport 2.x, v2.10.0

#1117 Added 2.10 release notes
  release-notes/opensearch-alerting.release-notes-2.10.0.0.md
Labels: backport 2.x, backport 2.10

#1122 optimize doc-level monitor workflow for index patterns
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/IndexUtils.kt
  alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
Labels: backport 2.10

#1139 add workflow null or empty check only when empty workflow id passed.
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetAlertsAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt
Labels: backport 2.x, backport 2.10
