Repository opensearch-project/alerting, pull requests merged in 2023-04, with the labels that each got.

#835 Added transport layer classes for getting and deleting the workflow
  alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDeleteWorkflowAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetWorkflowAction.kt
  alerting/src/test/kotlin/org/opensearch/alerting/WorkflowMonitorIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/transport/WorkflowSingleNodeTestCase.kt
Labels: composite-monitors

#845 Fixed transformation of document field names before running percolator search
  alerting/build.gradle
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt
Labels: backport 2.x, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#858 Use latest common-utils snapshot
  core/build.gradle
Labels: backport 2.x

#849 Update config index schema if needed at the start of each monitor execution
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt
Labels: backport 2.x, backport 2.5, backport 2.6, backport 2.7

#864 Added 2.7 release notes.
  release-notes/opensearch-alerting.release-notes-2.7.0.0.md
Labels: backport 2.x, backport 2.7

#870 Fix getAlerts API for standard Alerting monitors
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt
Labels: backport 2.x, backport 2.7

#878 integrate security-analytics & alerting for correlation engine
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/main/resources/org/opensearch/alerting/alerts/finding_mapping.json
  alerting/src/test/kotlin/org/opensearch/alerting/alerts/AlertIndicesIT.kt
Labels: backport 2.x, backport 2.7

#818 Baseline codeowners and maintainers
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x
