Repository opensearch-project/alerting, pull requests merged in 2024-04, with the labels that each got.

#1506 Add validation check for doc level query name during monitor creation
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexMonitorAction.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/MonitorRestApiIT.kt
Labels: backport 2.x, backport 2.13

#1510 Added input validation, and fixed bug for cross cluster monitors.
  alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt
  alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/QueryLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/GetRemoteIndexesRequest.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/GetRemoteIndexesResponse.kt
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestExecuteMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetRemoteIndexesAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetRemoteIndexesAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/IndexUtils.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatIndicesHelpers.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatShardsHelpers.kt
  alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt
  alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/action/GetRemoteIndexesActionTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/transport/GetRemoteIndexesActionIT.kt
Labels: backport 2.x, backport 2.12, backport 2.13

#1515 [Backport 2.x] Added input validation, and fixed bug for cross cluster monitors. (#1510)
  alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt
  alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/QueryLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/GetRemoteIndexesRequest.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/GetRemoteIndexesResponse.kt
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestExecuteMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetRemoteIndexesAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestIndexMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetRemoteIndexesAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/IndexUtils.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatIndicesHelpers.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/clusterMetricsMonitorHelpers/CatShardsHelpers.kt
  alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt
  alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/action/GetRemoteIndexesActionTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/transport/GetRemoteIndexesActionIT.kt
Labels: backport 2.13

#1496 doc-level monitor fan-out approach
  alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt
  alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerExecutionContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/QueryLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/DocLevelMonitorFanOutAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/DocLevelMonitorFanOutRequest.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/DocLevelMonitorFanOutResponse.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/ExecuteMonitorRequest.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/ExecuteWorkflowRequest.kt
  alerting/src/main/kotlin/org/opensearch/alerting/model/DocumentLevelTriggerRunResult.kt
  alerting/src/main/kotlin/org/opensearch/alerting/model/IndexExecutionContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDocLevelMonitorFanOutAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteWorkflowAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingException.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/CompositeWorkflowRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/WorkflowRunContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/WorkflowRunner.kt
  alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt
  alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt
  alerting/src/test/kotlin/org/opensearch/alerting/action/DocLevelMonitorFanOutRequestTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/action/DocLevelMonitorFanOutResponseTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/action/GetFindingsRequestTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/bwc/AlertingBackwardsCompatibilityIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/model/WriteableTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/triggeraction/TriggerExpressionResolverTests.kt
  alerting/src/test/resources/sample.pem
  alerting/src/test/resources/test-kirk.jks
Labels: backport 2.x, backport 2.13

#1521 doc-level monitor fan-out approach
  alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt
  alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerExecutionContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/QueryLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/DocLevelMonitorFanOutAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/DocLevelMonitorFanOutRequest.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/DocLevelMonitorFanOutResponse.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/ExecuteMonitorRequest.kt
  alerting/src/main/kotlin/org/opensearch/alerting/action/ExecuteWorkflowRequest.kt
  alerting/src/main/kotlin/org/opensearch/alerting/model/DocumentLevelTriggerRunResult.kt
  alerting/src/main/kotlin/org/opensearch/alerting/model/IndexExecutionContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportDocLevelMonitorFanOutAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteMonitorAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportExecuteWorkflowAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetWorkflowAlertsAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingException.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/CompositeWorkflowRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/WorkflowRunContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/workflow/WorkflowRunner.kt
  alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt
  alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt
  alerting/src/test/kotlin/org/opensearch/alerting/action/DocLevelMonitorFanOutRequestTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/action/DocLevelMonitorFanOutResponseTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/action/GetFindingsRequestTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/model/WriteableTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureWorkflowRestApiIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/triggeraction/TriggerExpressionResolverTests.kt
  alerting/src/test/resources/sample.pem
  alerting/src/test/resources/test-kirk.jks
Labels: backport 2.13

#1528 Adjusted integ tests for when security is enabled.
  alerting/src/test/kotlin/org/opensearch/alerting/transport/GetRemoteIndexesActionIT.kt
Labels: backport 2.x, backport 2.13

#1531 Adjusted maven publish workflow to execute automatically when merging a PR.
  .github/workflows/maven-publish.yml
Labels: backport 1.3, backport 2.x, backport 2.14
