Repository opensearch-project/alerting, pull requests merged in 2024-07, with the labels that each got.

#1584 Register system index descriptors through SystemIndexPlugin.getSystemIndexDescriptors
  alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt
Labels: backport 2.x

#1612 Enable cross-cluster monitor cluster setting
  alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt
  alerting/src/test/kotlin/org/opensearch/alerting/transport/GetRemoteIndexesActionIT.kt
Labels: backport 2.x, backport 2.14, backport 2.15

#1613 [Backport] Enable cross-cluster monitor cluster setting #1612
  alerting/src/main/kotlin/org/opensearch/alerting/settings/AlertingSettings.kt
  alerting/src/test/kotlin/org/opensearch/alerting/transport/GetRemoteIndexesActionIT.kt
Labels: backport 2.14, backport 2.15

#1619 added release notes for alerting
  release-notes/opensearch-alerting.release-notes-2.16.0.0.md
Labels: backport 2.x, backport 2.16

#1627 [Backport 2.x] fix monitor renew lock issue
  .github/workflows/security-test-workflow.yml
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerService.kt
  alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt
  alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
  core/src/main/kotlin/org/opensearch/alerting/core/lock/LockService.kt
Labels: backport 2.15, backport 2.16
