Repository opensearch-project/alerting, pull requests merged in 2024-02, with the labels that each got.

#1399 removed default admin credentials for alerting
  .github/workflows/security-test-workflow.yml
  DEVELOPER_GUIDE.md
Labels: backport 2.x, v2.12.0

#1416 Added engechas as a maintainer.
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x

#1432 fix for MapperException[the [enabled] parameter can't be updated for the object mapping [metadata.source_to_query_index_mapping]
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorMetadataService.kt
Labels: backport 2.x

#1447 Adjusted dependency versions to address CVEs.
  alerting/build.gradle
  build.gradle
Labels: v1.3.15
