Repository opensearch-project/alerting, pull requests merged in 2024-03, with the labels that each got.

#1448 Add 1.3.15 release notes
  release-notes/opensearch-alerting.release-notes-1.3.15.0.md
Labels: v1.3.15

#1425 Add an _exists_ check to document level monitor queries
  alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt
  alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
Labels: backport 2.x

#1464 Findings API Enhancements changes and integ tests fix
  alerting/src/main/kotlin/org/opensearch/alerting/resthandler/RestGetFindingsAction.kt
  alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetFindingsAction.kt
  alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
Labels: backport 2.x

#1450 Enhance per bucket, and per document monitor notification message ctx.
  alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerExecutionContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/model/AlertContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/script/BucketLevelTriggerExecutionContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/script/DocumentLevelTriggerExecutionContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/AggregationQueryRewriter.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt
  alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerServiceIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt
  alerting/src/test/kotlin/org/opensearch/alerting/model/AlertContextTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/util/AlertingUtilsTests.kt
Labels: backport 2.x

#1477 [Backport 2.x] Enhance per bucket, and per document monitor notification message ctx. (#1450)
  alerting/src/main/kotlin/org/opensearch/alerting/BucketLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/InputService.kt
  alerting/src/main/kotlin/org/opensearch/alerting/MonitorRunnerExecutionContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/model/AlertContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/script/BucketLevelTriggerExecutionContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/script/DocumentLevelTriggerExecutionContext.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/AggregationQueryRewriter.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/AlertingUtils.kt
  alerting/src/test/kotlin/org/opensearch/alerting/DocumentMonitorRunnerIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorRunnerServiceIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/TestHelpers.kt
  alerting/src/test/kotlin/org/opensearch/alerting/model/AlertContextTests.kt
  alerting/src/test/kotlin/org/opensearch/alerting/util/AlertingUtilsTests.kt
Labels: v2.13.0
