Repository opensearch-project/alerting, pull requests merged in 2024-10, with the labels that each got.

#1659 Adding Alerting Comments system indices and Security ITs
  alerting/src/main/kotlin/org/opensearch/alerting/AlertingPlugin.kt
  alerting/src/test/kotlin/org/opensearch/alerting/AccessRoles.kt
  alerting/src/test/kotlin/org/opensearch/alerting/AlertingRestTestCase.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/AlertingCommentsRestApiIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureAlertingCommentsRestApiIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/resthandler/SecureAlertingNotesRestApiIT.kt
Labels: backport 2.x

#1685 delete query index only if put mappings throws an exception
  alerting/src/main/kotlin/org/opensearch/alerting/DocumentLevelMonitorRunner.kt
  alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt
  sample-remote-monitor-plugin/src/main/java/org/opensearch/alerting/SampleRemoteMonitorRestHandler.java
Labels: backport 2.x, backport 2.15, backport 2.17

#1702 fix number of shards of query index to 0 and auto expand replicas to 0-1
  alerting/src/main/kotlin/org/opensearch/alerting/util/DocLevelMonitorQueries.kt
  alerting/src/test/kotlin/org/opensearch/alerting/MonitorDataSourcesIT.kt
  alerting/src/test/kotlin/org/opensearch/alerting/transport/AlertingSingleNodeTestCase.kt
Labels: backport 2.x, backport 2.15, backport 2.17

#1718 Added 2.18.0 release notes.
  release-notes/opensearch-alerting.release-notes-2.18.0.0.md
Labels: backport 2.x, v2.18.0, backport 2.18
