Repository opensearch-project/alerting, pull requests merged in 2025-02, with the labels that each got.

#1790 Added 2.19 release notes.
  release-notes/opensearch-alerting.release-notes-2.19.0.0.md
Labels: backport 2.x, v2.19.0, backport 2.19

#1802 bump logback to 1.5.16
  build.gradle
Labels: backport 2.19

#1804 2.19.1 release notes added
  release-notes/opensearch-alerting.release-notes-2.19.1.0.md
Labels: backport 2.x, backport 2.19
